name: Build Clash for iOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 仅当有 Podfile 时启用
      - name: Install CocoaPods (if Podfile exists)
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          else
            echo "No Podfile found, skipping CocoaPods."
          fi

      - name: Build .xcarchive
        run: |
          xcodebuild -project Clash.xcodeproj -scheme Clash -configuration Release -archivePath build/Clash.xcarchive archive
    
      - name: Export .ipa
        run: |
          xcodebuild -exportArchive -archivePath build/Clash.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/ipa

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clash.ipa
          path: build/ipa/Clash.ipa
